spring:

  #  h2:
  #    console:
  #      enabled: true

  datasource:
    #    url: jdbc:mysql://clone.cvoggurhiwh9.ap-northeast-2.rds.amazonaws.com:3306/clonepj
    url: jdbc:mysql://viva-db.cvoggurhiwh9.ap-northeast-2.rds.amazonaws.com:3306/myselectshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Viva
    password: Aa1011303^^

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

  logging:
    level:
      com.clone.daangncole: DEBUG